# Generated by Django 5.0.4 on 2024-04-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_producto_nombre_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
