# Generated by Django 5.0.4 on 2024-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(verbose_name='Stock en deposito'),
        ),
    ]
