# Generated by Django 5.0.4 on 2024-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_alter_producto_stock_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(help_text='Ingresar cantidad neta en deposito', verbose_name='Stock en deposito'),
        ),
    ]
